-- MySQL Script generated by MySQL Workbench
-- Ter 21 Fev 2017 09:37:52 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `Cpf` VARCHAR(11) NOT NULL,
  `PrimeiroNome` VARCHAR(45) NOT NULL,
  `NomeMeio` VARCHAR(45) NOT NULL,
  `UltimoNome` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`Cpf`),
  UNIQUE INDEX `Cpf_UNIQUE` (`Cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Barbearia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Barbearia` (
  `CNPJ` VARCHAR(14) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Rua` VARCHAR(45) NOT NULL,
  `Bairro` VARCHAR(45) NOT NULL,
  `Complemento` VARCHAR(45) NULL,
  `Imagem` CHAR(32) NULL,
  PRIMARY KEY (`CNPJ`),
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Serviço` (
  `idServiço` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Descrição` VARCHAR(45) NULL,
  `TempoMedio` INT NOT NULL,
  `Barbearia_CNPJ` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`idServiço`, `Barbearia_CNPJ`),
  INDEX `fk_Serviço_Barbearia1_idx` (`Barbearia_CNPJ` ASC),
  UNIQUE INDEX `idServiço_UNIQUE` (`idServiço` ASC),
  CONSTRAINT `fk_Serviço_Barbearia1`
    FOREIGN KEY (`Barbearia_CNPJ`)
    REFERENCES `mydb`.`Barbearia` (`CNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Agenda` (
  `idAgenda` INT NOT NULL,
  `Data` DATE NOT NULL,
  `Horario` TIME NOT NULL,
  `Cliente_Cpf` VARCHAR(11) NOT NULL,
  `Serviço_idServiço` INT NOT NULL,
  `Serviço_Barbearia_CNPJ` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`idAgenda`, `Cliente_Cpf`, `Serviço_idServiço`, `Serviço_Barbearia_CNPJ`),
  INDEX `fk_Agenda_Cliente1_idx` (`Cliente_Cpf` ASC),
  INDEX `fk_Agenda_Serviço1_idx` (`Serviço_idServiço` ASC, `Serviço_Barbearia_CNPJ` ASC),
  UNIQUE INDEX `idAgenda_UNIQUE` (`idAgenda` ASC),
  CONSTRAINT `fk_Agenda_Cliente1`
    FOREIGN KEY (`Cliente_Cpf`)
    REFERENCES `mydb`.`Cliente` (`Cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Agenda_Serviço1`
    FOREIGN KEY (`Serviço_idServiço` , `Serviço_Barbearia_CNPJ`)
    REFERENCES `mydb`.`Serviço` (`idServiço` , `Barbearia_CNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Barbeiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Barbeiro` (
  `IDFuncionario` INT NOT NULL,
  `PrimeiroNome` VARCHAR(45) NOT NULL,
  `NomeMeio` VARCHAR(45) NOT NULL,
  `UltimoNome` VARCHAR(45) NOT NULL,
  `Especialidade` VARCHAR(45) NULL,
  `Barbearia_CNPJ` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`IDFuncionario`, `Barbearia_CNPJ`),
  INDEX `fk_Barbeiro_Barbearia1_idx` (`Barbearia_CNPJ` ASC),
  UNIQUE INDEX `IDFuncionario_UNIQUE` (`IDFuncionario` ASC),
  CONSTRAINT `fk_Barbeiro_Barbearia1`
    FOREIGN KEY (`Barbearia_CNPJ`)
    REFERENCES `mydb`.`Barbearia` (`CNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
